const bi = (ru, uz) => ({ ru, uz });

// Grades 9–11: standard tests and written mathematical answers from the learner's keyboard.
export const mathTestItems911 = [
  { id: "g9-quadratic", grade: 9, domain: "algebra", type: "choice", skill: bi("Квадратные уравнения", "Kvadrat tenglamalar"), prompt: bi("Сколько корней имеет уравнение x² + 4x + 5 = 0?", "x² + 4x + 5 = 0 tenglama nechta haqiqiy ildizga ega?"), options: ["0", "1", "2", "Бесконечно много"], answer: "0" },
  { id: "g9-system", grade: 9, domain: "algebra", type: "text", skill: bi("Система уравнений", "Tenglamalar sistemasi"), prompt: bi("Найди x: x + y = 11, x − y = 5.", "x ni toping: x + y = 11, x − y = 5."), answer: "8" },
  { id: "g9-inequality", grade: 9, domain: "algebra", type: "choice", skill: bi("Неравенства", "Tengsizliklar"), prompt: bi("Решение неравенства 3x − 6 > 0", "3x − 6 > 0 tengsizlikning yechimi"), options: ["x > 2", "x < 2", "x > −2", "x < −2"], answer: "x > 2" },
  { id: "g9-root", grade: 9, domain: "algebra", type: "text", skill: bi("Корни и степени", "Ildizlar va darajalar"), prompt: bi("Вычисли: √196 − 3²", "Hisoblang: √196 − 3²"), answer: "5" },
  { id: "g9-geometry", grade: 9, domain: "geometry", type: "choice", skill: bi("Подобие треугольников", "Uchburchaklar o‘xshashligi"), prompt: bi("Стороны подобных треугольников относятся как 2:5. Меньшая сторона равна 8. Найди соответствующую большую сторону.", "O‘xshash uchburchaklar tomonlari 2:5 nisbatda. Kichik tomon 8 ga teng. Katta tomonni toping."), options: ["16", "20", "24", "32"], answer: "20" },
  { id: "g9-function", grade: 9, domain: "functions", type: "choice", skill: bi("Квадратичная функция", "Kvadrat funksiya"), prompt: bi("Вершина параболы y = (x − 2)² + 3 имеет координаты", "y = (x − 2)² + 3 parabolasining uchi koordinatalari"), options: ["(−2; 3)", "(2; −3)", "(2; 3)", "(−2; −3)"], answer: "(2; 3)" },
  { id: "g10-degree", grade: 10, domain: "algebra", type: "text", skill: bi("Степени", "Darajalar"), prompt: bi("Вычисли: 2³ × 2⁴", "Hisoblang: 2³ × 2⁴"), answer: "128" },
  { id: "g10-log", grade: 10, domain: "algebra", type: "choice", skill: bi("Логарифмы", "Logarifmlar"), prompt: bi("log₂ 32 равен", "log₂ 32 nimaga teng?"), options: ["4", "5", "6", "16"], answer: "5" },
  { id: "g10-trig", grade: 10, domain: "geometry", type: "choice", skill: bi("Тригонометрия", "Trigonometriya"), prompt: bi("sin 30° равен", "sin 30° nimaga teng?"), options: ["0", "1/2", "√2/2", "1"], answer: "1/2" },
  { id: "g10-progress", grade: 10, domain: "number", type: "text", skill: bi("Арифметическая прогрессия", "Arifmetik progressiya"), prompt: bi("В арифметической прогрессии a₁ = 4, d = 3. Найди a₅.", "Arifmetik progressiyada a₁ = 4, d = 3. a₅ ni toping."), answer: "16" },
  { id: "g10-probability", grade: 10, domain: "probability", type: "choice", skill: bi("Вероятность", "Ehtimollik"), prompt: bi("Монету бросают два раза. Вероятность двух орлов равна", "Tanga ikki marta tashlanadi. Ikki marta gerb tushish ehtimoli"), options: ["1/2", "1/3", "1/4", "3/4"], answer: "1/4" },
  { id: "g10-circle", grade: 10, domain: "geometry", type: "text", skill: bi("Длина окружности", "Aylana uzunligi"), prompt: bi("Радиус окружности 5. Какой коэффициент стоит перед π в её длине?", "Aylana radiusi 5. Uning uzunligida π oldidagi koeffitsiyent qancha?"), answer: "10" },
  { id: "g11-derivative", grade: 11, domain: "functions", type: "choice", skill: bi("Производная", "Hosila"), prompt: bi("Производная функции f(x) = x³ равна", "f(x) = x³ funksiyasining hosilasi"), options: ["x²", "2x", "3x²", "3x"], answer: "3x²" },
  { id: "g11-limit", grade: 11, domain: "functions", type: "text", skill: bi("Предел", "Limit"), prompt: bi("Вычисли: lim x→0 (sin x)/x", "Hisoblang: lim x→0 (sin x)/x"), answer: "1" },
  { id: "g11-integral", grade: 11, domain: "functions", type: "choice", skill: bi("Первообразная", "Boshlang‘ich funksiya"), prompt: bi("Одна из первообразных функции 2x равна", "2x funksiyasining boshlang‘ich funksiyalaridan biri"), options: ["x²", "2x²", "x² + C", "2x + C"], answer: "x² + C" },
  { id: "g11-combinatorics", grade: 11, domain: "probability", type: "text", skill: bi("Комбинаторика", "Kombinatorika"), prompt: bi("Сколькими способами можно выбрать 2 учеников из 5?", "5 o‘quvchidan 2 tasini necha usulda tanlash mumkin?"), answer: "10" },
  { id: "g11-vector", grade: 11, domain: "geometry", type: "choice", skill: bi("Векторы", "Vektorlar"), prompt: bi("Скалярное произведение (2; 1) и (3; 4) равно", "(2; 1) va (3; 4) vektorlarining skalyar ko‘paytmasi"), options: ["7", "10", "14", "18"], answer: "10" },
  { id: "g11-exponent", grade: 11, domain: "algebra", type: "choice", skill: bi("Показательные уравнения", "Ko‘rsatkichli tenglamalar"), prompt: bi("Реши: 3ˣ = 27", "Yeching: 3ˣ = 27"), options: ["2", "3", "6", "9"], answer: "3" },
  { id: "g11-derivative-value", grade: 11, domain: "functions", type: "text", skill: bi("Значение производной", "Hosila qiymati"), prompt: bi("Для f(x) = x² − 4x найди f′(3).", "f(x) = x² − 4x uchun f′(3) ni toping."), answer: "2" },
  { id: "g11-stereometry", grade: 11, domain: "geometry", type: "text", skill: bi("Объём призмы", "Prizma hajmi"), prompt: bi("Площадь основания призмы 12 см², высота 7 см. Найди объём.", "Prizma asosining yuzi 12 sm², balandligi 7 sm. Hajmini toping."), answer: "84" },
];
