const bi = (ru, uz) => ({ ru, uz });

// Grades 5–8: standard single-answer items plus written responses from the learner's keyboard.
export const mathTestItems58 = [
  { id: "g5-fraction", grade: 5, domain: "number", type: "choice", skill: bi("Обыкновенные дроби", "Oddiy kasrlar"), prompt: bi("Чему равна сумма 3/8 + 1/8?", "3/8 + 1/8 yig‘indisi nimaga teng?"), options: ["1/2", "4/8", "3/16", "4/16"], answer: "1/2" },
  { id: "g5-decimal", grade: 5, domain: "number", type: "text", skill: bi("Десятичные дроби", "O‘nli kasrlar"), prompt: bi("Вычисли: 4,7 + 2,35", "Hisoblang: 4,7 + 2,35"), answer: "7,05" },
  { id: "g5-equation", grade: 5, domain: "algebra", type: "choice", skill: bi("Простое уравнение", "Sodda tenglama"), prompt: bi("Найди x: x + 17 = 42", "x ni toping: x + 17 = 42"), options: ["25", "59", "17", "24"], answer: "25" },
  { id: "g5-percent", grade: 5, domain: "number", type: "text", skill: bi("Проценты", "Foizlar"), prompt: bi("Найди 20% от 150.", "150 ning 20% ini toping."), answer: "30" },
  { id: "g5-area", grade: 5, domain: "geometry", type: "choice", skill: bi("Площадь прямоугольника", "To‘g‘ri to‘rtburchak yuzasi"), prompt: bi("Длина прямоугольника 9 см, ширина 4 см. Чему равна площадь?", "To‘g‘ri to‘rtburchak uzunligi 9 sm, eni 4 sm. Yuzasi qancha?"), options: ["13", "26", "36", "72"], answer: "36" },
  { id: "g6-negative", grade: 6, domain: "number", type: "choice", skill: bi("Целые числа", "Butun sonlar"), prompt: bi("Вычисли: −7 + 12", "Hisoblang: −7 + 12"), options: ["−19", "−5", "5", "19"], answer: "5" },
  { id: "g6-ratio", grade: 6, domain: "algebra", type: "text", skill: bi("Отношения", "Nisbatlar"), prompt: bi("Сократи отношение 18:24. Напиши два числа через двоеточие.", "18:24 nisbatni qisqartiring. Ikki sonni ikki nuqta orqali yozing."), answer: "3:4" },
  { id: "g6-expression", grade: 6, domain: "algebra", type: "choice", skill: bi("Раскрытие скобок", "Qavslarni ochish"), prompt: bi("Упрости: 3(a + 2)", "Soddalashtiring: 3(a + 2)"), options: ["3a + 2", "3a + 6", "a + 6", "6a"], answer: "3a + 6" },
  { id: "g6-divisibility", grade: 6, domain: "reasoning", type: "choice", skill: bi("Признаки делимости", "Bo‘linish alomatlari"), prompt: bi("Какое число делится на 9?", "Qaysi son 9 ga bo‘linadi?"), options: ["234", "245", "352", "416"], answer: "234" },
  { id: "g6-proportion", grade: 6, domain: "algebra", type: "text", skill: bi("Пропорция", "Proporsiya"), prompt: bi("Реши пропорцию: x/5 = 12/20", "Proporsiyani yeching: x/5 = 12/20"), answer: "3" },
  { id: "g7-linear", grade: 7, domain: "algebra", type: "text", skill: bi("Линейное уравнение", "Chiziqli tenglama"), prompt: bi("Реши: 4x − 9 = 19", "Yeching: 4x − 9 = 19"), answer: "7" },
  { id: "g7-percent", grade: 7, domain: "number", type: "choice", skill: bi("Изменение на процент", "Foizga o‘zgarish"), prompt: bi("Цена 80 000 сум увеличилась на 10%. Какая стала цена?", "80 000 so‘mlik narx 10% ga oshdi. Yangi narx qancha?"), options: ["72 000", "80 800", "88 000", "90 000"], answer: "88 000" },
  { id: "g7-angle", grade: 7, domain: "geometry", type: "choice", skill: bi("Сумма углов треугольника", "Uchburchak burchaklari yig‘indisi"), prompt: bi("В треугольнике два угла 48° и 67°. Найди третий угол.", "Uchburchakning ikki burchagi 48° va 67°. Uchinchi burchakni toping."), options: ["55°", "65°", "75°", "115°"], answer: "65°" },
  { id: "g7-coordinate", grade: 7, domain: "functions", type: "text", skill: bi("Координатная прямая", "Koordinata to‘g‘ri chizig‘i"), prompt: bi("Какое число находится на 3 единицы правее числа −5?", "−5 sonidan 3 birlik o‘ngda qaysi son turadi?"), answer: "-2" },
  { id: "g7-probability", grade: 7, domain: "probability", type: "choice", skill: bi("Простая вероятность", "Sodda ehtimollik"), prompt: bi("В коробке 3 красных и 2 синих шара. Вероятность достать синий шар?", "Qutida 3 ta qizil va 2 ta ko‘k shar bor. Ko‘k shar olish ehtimoli qanday?"), options: ["2/3", "2/5", "3/5", "1/2"], answer: "2/5" },
  { id: "g8-pythagoras", grade: 8, domain: "geometry", type: "text", skill: bi("Теорема Пифагора", "Pifagor teoremasi"), prompt: bi("Катеты прямоугольного треугольника равны 6 и 8. Найди гипотенузу.", "To‘g‘ri burchakli uchburchak katetlari 6 va 8. Gipotenuzani toping."), answer: "10" },
  { id: "g8-system", grade: 8, domain: "algebra", type: "choice", skill: bi("Система уравнений", "Tenglamalar sistemasi"), prompt: bi("Решение системы: x + y = 9, x − y = 3", "Sistema yechimi: x + y = 9, x − y = 3"), options: ["x=3, y=6", "x=6, y=3", "x=9, y=3", "x=6, y=9"], answer: "x=6, y=3" },
  { id: "g8-square", grade: 8, domain: "algebra", type: "choice", skill: bi("Квадратное уравнение", "Kvadrat tenglama"), prompt: bi("Корни уравнения x² − 9 = 0", "x² − 9 = 0 tenglamaning ildizlari"), options: ["3", "−3", "3 и −3", "9 и −9"], answer: "3 и −3" },
  { id: "g8-function", grade: 8, domain: "functions", type: "text", skill: bi("Линейная функция", "Chiziqli funksiya"), prompt: bi("Для y = 2x − 1 найди y при x = 5.", "y = 2x − 1 da x = 5 bo‘lsa, y ni toping."), answer: "9" },
  { id: "g8-root", grade: 8, domain: "algebra", type: "text", skill: bi("Арифметический квадратный корень", "Arifmetik kvadrat ildiz"), prompt: bi("Вычисли √144.", "√144 ni hisoblang."), answer: "12" },
];
